/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/apple/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apple Notifications */
        post: operations["apple_notifications_api_v1_auth_apple_notifications_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/authorize/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Authorize */
        get: operations["authorize_api_v1_auth_authorize__provider__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Consents */
        get: operations["list_consents_api_v1_auth_consents_get"];
        put?: never;
        /** Submit Consents */
        post: operations["submit_consents_api_v1_auth_consents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/link/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Link Provider */
        post: operations["link_provider_api_v1_auth_link__provider__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login/{provider}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login__provider__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Feedback
         * @description 결과 채택 신호만 남긴다(원문 없음). 본인 요청의 로그에만 기록된다.
         */
        post: operations["feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reply/interpret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Interpret */
        post: operations["interpret_api_v1_reply_interpret_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tone/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_api_v1_tone_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tone/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Options */
        get: operations["options_api_v1_tone_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tone/transform": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transform */
        post: operations["transform_api_v1_tone_transform_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        /** Delete Me */
        delete: operations["delete_me_api_v1_users_me_delete"];
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_v1_users_me_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppleName */
        AppleName: {
            /** Firstname */
            firstName?: string | null;
            /** Lastname */
            lastName?: string | null;
        };
        /** AppleUser */
        AppleUser: {
            name?: components["schemas"]["AppleName"] | null;
        };
        /** AuthTokenResponse */
        AuthTokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Is New User */
            is_new_user: boolean;
            /** Refresh Expires In */
            refresh_expires_in?: number | null;
            /** Refresh Token */
            refresh_token?: string | null;
            /** Required Consents */
            required_consents?: components["schemas"]["RequiredConsent"][];
            /**
             * Token Type
             * @default Bearer
             * @constant
             */
            token_type?: "Bearer";
            user: components["schemas"]["UserProfile"];
        };
        /** AuthorizeResponse */
        AuthorizeResponse: {
            /** Authorize Url */
            authorize_url: string;
            /** Expires In */
            expires_in: number;
            /** State */
            state: string;
        };
        /** Body_apple_notifications_api_v1_auth_apple_notifications_post */
        Body_apple_notifications_api_v1_auth_apple_notifications_post: {
            /** Payload */
            payload: string;
        };
        /** ConsentItem */
        ConsentItem: {
            /** Agreed */
            agreed: boolean;
            type: components["schemas"]["ConsentType"];
            /** Version */
            version: string;
        };
        /** ConsentListResponse */
        ConsentListResponse: {
            /** Consents */
            consents: components["schemas"]["ConsentState"][];
        };
        /** ConsentState */
        ConsentState: {
            /** Agreed */
            agreed: boolean;
            type: components["schemas"]["ConsentType"];
            /** Version */
            version: string;
        };
        /** ConsentSubmitRequest */
        ConsentSubmitRequest: {
            /** Consents */
            consents: components["schemas"]["ConsentItem"][];
        };
        /**
         * ConsentType
         * @enum {string}
         */
        ConsentType: "terms_of_service" | "privacy_policy" | "age_over_14" | "marketing" | "quality_log_collection";
        /** EmotionLabel */
        EmotionLabel: {
            /**
             * Name
             * @enum {string}
             */
            name: "anger" | "frustration" | "sadness" | "anxiety" | "joy" | "affection" | "neutral" | "indifference";
            /** Score */
            score: number;
        };
        /** EmotionOut */
        EmotionOut: {
            /** Labels */
            labels: components["schemas"]["EmotionLabel"][];
            /** Temperature */
            temperature: number;
            /**
             * Zone
             * @enum {string}
             */
            zone: "cold" | "calm" | "warning" | "danger";
        };
        /** FeedbackRequest */
        FeedbackRequest: {
            /**
             * Action
             * @enum {string}
             */
            action: "copied" | "shared" | "thumbs_up" | "thumbs_down";
            /** Reason */
            reason?: ("intent_changed" | "too_formal" | "too_casual" | "unnatural" | "other") | null;
            /** Request Id */
            request_id: string;
            /** Variant Kind */
            variant_kind?: ("primary" | "softer" | "concise" | "confirm" | "empathize" | "light_shift") | null;
        };
        /** Guide */
        Guide: {
            /** Avoid */
            avoid: string[];
            /** Check Points */
            check_points: string[];
            /** Overthinking Warning */
            overthinking_warning: boolean;
            /** Summary */
            summary: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Intent */
        Intent: {
            /** Confidence */
            confidence: number;
            /**
             * Label
             * @enum {string}
             */
            label: "accept" | "decline" | "request" | "apology" | "inform" | "complain" | "gratitude" | "other";
        };
        /** Interpretation */
        Interpretation: {
            /** Likelihood */
            likelihood: number;
            /** Signals */
            signals: string[];
            /** Summary */
            summary: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token?: string | null;
        };
        /** PersonaOut */
        PersonaOut: {
            /** Description */
            description: string;
            /** Display Name */
            display_name: string;
            /** Icon */
            icon: string | null;
            /** Key */
            key: string;
        };
        /** RedFlagOut */
        RedFlagOut: {
            /** End */
            end: number;
            /** Reason */
            reason: string;
            /**
             * Severity
             * @enum {string}
             */
            severity: "low" | "medium" | "high";
            /**
             * Start
             * @description draft 기준 UTF-16 code unit 오프셋
             */
            start: number;
            /** Suggestion */
            suggestion: string;
            /** Text */
            text: string;
            /**
             * Type
             * @enum {string}
             */
            type: "sarcasm" | "blame" | "command" | "passive_aggressive" | "belittling" | "absolute" | "ambiguous" | "cold";
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** ReplyInterpretRequest */
        ReplyInterpretRequest: {
            /** Conversation */
            conversation?: components["schemas"]["Turn"][];
            /** Message */
            message: string;
            /** My Concern */
            my_concern?: string | null;
            /**
             * Relation
             * @enum {string}
             */
            relation: "work_superior" | "work_peer" | "client" | "partner" | "family" | "friend" | "acquaintance";
            /**
             * Target Lang
             * @default ko
             * @enum {string}
             */
            target_lang?: "ko" | "en" | "ja";
        };
        /** ReplyInterpretResponse */
        ReplyInterpretResponse: {
            /** Disclaimer */
            disclaimer: string;
            guide: components["schemas"]["Guide"];
            /** Interpretations */
            interpretations: components["schemas"]["Interpretation"][];
            message_emotion: components["schemas"]["EmotionOut"];
            /** Request Id */
            request_id: string;
            /** Suggested Replies */
            suggested_replies: components["schemas"]["SuggestedReplyOut"][];
        };
        /** RequiredConsent */
        RequiredConsent: {
            type: components["schemas"]["ConsentType"];
            /** Url */
            url: string | null;
            /** Version */
            version: string;
        };
        /** SocialLoginRequest */
        SocialLoginRequest: {
            apple_user?: components["schemas"]["AppleUser"] | null;
            /** Code */
            code?: string | null;
            /** Code Verifier */
            code_verifier: string;
            /** Consents */
            consents?: components["schemas"]["ConsentItem"][];
            /** Device Info */
            device_info?: string | null;
            /** Handoff */
            handoff?: string | null;
            /** Redirect Uri */
            redirect_uri: string;
            /** State */
            state?: string | null;
        };
        /**
         * SocialProvider
         * @enum {string}
         */
        SocialProvider: "kakao" | "google" | "naver" | "apple";
        /** SuggestedReplyOut */
        SuggestedReplyOut: {
            /** Rationale */
            rationale: string;
            /**
             * Style
             * @enum {string}
             */
            style: "confirm" | "empathize" | "light_shift";
            /** Text */
            text: string;
        };
        /** TokenRefreshResponse */
        TokenRefreshResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Expires In */
            refresh_expires_in: number;
            /** Refresh Token */
            refresh_token?: string | null;
            /**
             * Token Type
             * @default Bearer
             * @constant
             */
            token_type?: "Bearer";
        };
        /** ToneAnalyzeRequest */
        ToneAnalyzeRequest: {
            /** Context */
            context?: string | null;
            /** Relation */
            relation?: ("work_superior" | "work_peer" | "client" | "partner" | "family" | "friend" | "acquaintance") | null;
            /** Text */
            text: string;
        };
        /** ToneAnalyzeResponse */
        ToneAnalyzeResponse: {
            emotion: components["schemas"]["EmotionOut"];
            /** Red Flags */
            red_flags: components["schemas"]["RedFlagOut"][];
            /** Request Id */
            request_id: string;
        };
        /** ToneOptionsResponse */
        ToneOptionsResponse: {
            /** Languages */
            languages: string[];
            /** Personas */
            personas: components["schemas"]["PersonaOut"][];
            /** Relations */
            relations: string[];
        };
        /** ToneTransformRequest */
        ToneTransformRequest: {
            /** Context */
            context?: string | null;
            /** Draft */
            draft: string;
            /**
             * Formality
             * @default auto
             * @enum {string}
             */
            formality?: "auto" | "high" | "medium" | "low";
            options?: components["schemas"]["TransformOptions"];
            /**
             * Persona
             * @enum {string}
             */
            persona: "affectionate" | "polite" | "polite_decline" | "concise_business" | "humorous" | "apology";
            /** Relation */
            relation?: ("work_superior" | "work_peer" | "client" | "partner" | "family" | "friend" | "acquaintance") | null;
            /**
             * Target Lang
             * @enum {string}
             */
            target_lang: "ko" | "en" | "ja";
        };
        /** ToneTransformResponse */
        ToneTransformResponse: {
            emotion: components["schemas"]["EmotionOut"];
            intent: components["schemas"]["Intent"];
            meta: components["schemas"]["TransformMeta"];
            /** Red Flags */
            red_flags: components["schemas"]["RedFlagOut"][];
            /** Request Id */
            request_id: string;
            /** Variants */
            variants: components["schemas"]["VariantOut"][];
        };
        /** TransformMeta */
        TransformMeta: {
            /** Latency Ms */
            latency_ms: number | null;
            /**
             * Model Tier
             * @enum {string}
             */
            model_tier: "light" | "heavy";
            /** Source Lang */
            source_lang: string;
            /** Target Lang */
            target_lang: string;
        };
        /** TransformOptions */
        TransformOptions: {
            /**
             * Emoji
             * @default light
             * @enum {string}
             */
            emoji?: "none" | "light" | "rich";
            /**
             * Include Rationale
             * @default true
             */
            include_rationale?: boolean;
        };
        /** Turn */
        Turn: {
            /** Sent At */
            sent_at?: string | null;
            /**
             * Speaker
             * @enum {string}
             */
            speaker: "me" | "them";
            /** Text */
            text: string;
        };
        /** UserProfile */
        UserProfile: {
            /** Default Target Lang */
            default_target_lang: string;
            /** Display Name */
            display_name: string | null;
            /** Email */
            email: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Private Email */
            is_private_email: boolean;
            /** Linked Providers */
            linked_providers: components["schemas"]["SocialProvider"][];
            /** Plan */
            plan: string;
            status: components["schemas"]["UserStatus"];
            /** Ui Locale */
            ui_locale: string;
        };
        /** UserResponse */
        UserResponse: {
            user: components["schemas"]["UserProfile"];
        };
        /**
         * UserStatus
         * @enum {string}
         */
        UserStatus: "active" | "suspended" | "pending_consent";
        /** UserUpdateRequest */
        UserUpdateRequest: {
            /** Default Target Lang */
            default_target_lang?: ("ko" | "en" | "ja") | null;
            /** Display Name */
            display_name?: string | null;
            /** Ui Locale */
            ui_locale?: ("ko" | "en" | "ja") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VariantOut */
        VariantOut: {
            /** Expected Temperature */
            expected_temperature: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "primary" | "softer" | "concise";
            /** Rationale */
            rationale: string | null;
            /** Text */
            text: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    apple_notifications_api_v1_auth_apple_notifications_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Body_apple_notifications_api_v1_auth_apple_notifications_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    authorize_api_v1_auth_authorize__provider__get: {
        parameters: {
            query: {
                code_challenge: string;
                code_challenge_method: "S256";
                redirect_uri: string;
            };
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_consents_api_v1_auth_consents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentListResponse"];
                };
            };
        };
    };
    submit_consents_api_v1_auth_consents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentSubmitRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    link_provider_api_v1_auth_link__provider__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login__provider__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocialLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthTokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefreshResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    interpret_api_v1_reply_interpret_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplyInterpretRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReplyInterpretResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_api_v1_tone_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToneAnalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToneAnalyzeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    options_api_v1_tone_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToneOptionsResponse"];
                };
            };
        };
    };
    transform_api_v1_tone_transform_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToneTransformRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToneTransformResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    delete_me_api_v1_users_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_me_api_v1_users_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
