"""llm tables

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-01 18:35:54.334275

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# llm_tier는 세 테이블에서 쓰인다. PostgreSQL에서 CREATE TYPE은 첫 테이블에서만 실행한다.
LLM_TIER_REUSED = sa.Enum("light", "heavy", name="llm_tier").with_variant(
    postgresql.ENUM("light", "heavy", name="llm_tier", create_type=False), "postgresql"
)

# revision identifiers, used by Alembic.
revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("system_prompt", sa.Text(), nullable=False),
        sa.Column("user_template", sa.Text(), nullable=False),
        sa.Column(
            "output_schema",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("model_tier", sa.Enum("light", "heavy", name="llm_tier"), nullable=False),
        sa.Column("effort", sa.String(length=10), nullable=True),
        sa.Column("max_tokens", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("rollout_percent", sa.SmallInteger(), nullable=False),
        sa.Column("created_by", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "rollout_percent BETWEEN 0 AND 100",
            name=op.f("ck_prompt_templates_rollout_percent_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prompt_templates")),
        sa.UniqueConstraint("name", "locale", "version", name="uq_prompt_version"),
    )
    op.create_index(
        "uq_prompt_active",
        "prompt_templates",
        ["name", "locale"],
        unique=True,
        postgresql_where=sa.text("is_active"),
        sqlite_where=sa.text("is_active"),
    )
    op.create_table(
        "tone_options",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("locale", sa.String(length=10), nullable=False),
        sa.Column("display_name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("prompt_directive", sa.Text(), nullable=False),
        sa.Column("default_tier", LLM_TIER_REUSED, nullable=False),
        sa.Column("icon", sa.String(length=40), nullable=True),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tone_options")),
        sa.UniqueConstraint("key", "locale", name="uq_tone_key_locale"),
    )
    op.create_table(
        "transformation_logs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("tone_transform", "tone_analyze", "reply_interpret", name="transform_kind"),
            nullable=False,
        ),
        sa.Column("tone_option_key", sa.String(length=40), nullable=True),
        sa.Column("prompt_template_id", sa.Uuid(), nullable=True),
        sa.Column("model_tier", LLM_TIER_REUSED, nullable=False),
        sa.Column("model_id", sa.String(length=60), nullable=False),
        sa.Column("source_lang", sa.String(length=10), nullable=True),
        sa.Column("target_lang", sa.String(length=10), nullable=True),
        sa.Column("masked_context", sa.Text(), nullable=True),
        sa.Column("masked_draft", sa.Text(), nullable=True),
        sa.Column(
            "masked_output",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "pii_types_detected",
            sa.JSON().with_variant(postgresql.ARRAY(sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("emotion_temperature", sa.SmallInteger(), nullable=True),
        sa.Column("red_flag_count", sa.SmallInteger(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "success",
                "guardrail_blocked",
                "llm_error",
                "schema_invalid",
                "refused",
                name="log_status",
            ),
            nullable=False,
        ),
        sa.Column("guardrail_score", sa.Double(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cached_tokens", sa.Integer(), nullable=True),
        sa.Column("ttft_ms", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("selected_variant", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "emotion_temperature BETWEEN 0 AND 100",
            name=op.f("ck_transformation_logs_emotion_temperature_range"),
        ),
        sa.ForeignKeyConstraint(
            ["prompt_template_id"],
            ["prompt_templates.id"],
            name=op.f("fk_transformation_logs_prompt_template_id_prompt_templates"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_transformation_logs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transformation_logs")),
    )
    op.create_index("ix_tlogs_created", "transformation_logs", ["created_at"], unique=False)
    op.create_index("ix_tlogs_expires", "transformation_logs", ["expires_at"], unique=False)
    op.create_index("ix_tlogs_user", "transformation_logs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_tlogs_user", table_name="transformation_logs")
    op.drop_index("ix_tlogs_expires", table_name="transformation_logs")
    op.drop_index("ix_tlogs_created", table_name="transformation_logs")
    op.drop_table("transformation_logs")
    op.drop_table("tone_options")
    op.drop_index(
        "uq_prompt_active",
        table_name="prompt_templates",
        postgresql_where=sa.text("is_active"),
        sqlite_where=sa.text("is_active"),
    )
    op.drop_table("prompt_templates")
    # ### end Alembic commands ###
    bind = op.get_bind()
    for enum_name in ("log_status", "transform_kind", "llm_tier"):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
